### ISSUE TITLE
alpha parameter

### ISSUE THREAD

**Issue by nrox** [nrox/q-learning.js#1]
Hi, @darraghmckay, what is the practical advantage of using an alpha parameter as in your fork https://github.com/darraghmckay/qlearner.js ?

**Comment by darraghmckay** [comment]
As per the wikipedia page, 
The alpha parameter is the learning rate of the learner. 

The learning rate determines to what extent the newly acquired information will override the old information. A factor of 0 will make the agent not learn anything, while a factor of 1 would make the agent consider only the most recent information.

So my fork modifies the learning algorithm to match the algorithm defined here: 
https://en.wikipedia.org/wiki/Q-learning#Algorithm

Your library was very useful but I needed to implement the alpha parameter for  the project I was working on. So thanks for the hard work.
I hope that makes a bit of sense.

**Comment by nrox** [comment]
This deserves being merged in the near future, as it is very handy in some situations.
Thanks.
